name: fluttertube
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: "^0.12.2"
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  # ext_video_player: ^0.0.6
  shared_preferences: ^2.0.13
  youtube_player_flutter: ^8.0.0
  # flutter_youtube: "^2.0.0+1"
  rxdart: ^0.27.3
  bloc_pattern: ^3.0.0 
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets: 
   - images/
